// Generated by CoffeeScript 1.6.3
(function() {
  var Gcalendar, instances;

  Gcalendar = require('./gcalendar');

  instances = {};

  exports.init = function(options, callback) {
    if (callback == null) {
      callback = function() {};
    }
  };

  exports.api = function(instance, query, callback) {
    if (callback == null) {
      callback = function() {};
    }
  };

}).call(this);
