// Generated by CoffeeScript 1.6.3
(function() {
  var $client, Client, axon, req, rpc;

  axon = require('axon');

  rpc = require('axon-rpc');

  req = axon.socket('req');

  $client = null;

  Client = (function() {
    Client.connect = function() {
      if ($client == null) {
        req.connect.apply(req, arguments);
        $client = new rpc.Client(req);
      }
      return this;
    };

    function Client(options) {
      $client.call('init', options, function(err, instance) {
        return this.instance = instance;
      });
    }

    Client.prototype.api = function(query) {
      var _api, _arguments,
        _this = this;
      _api = {};
      _arguments = [];
      $client.call(this.instance, query);
      _api.execute = function(callback) {
        if (callback == null) {
          callback = function() {};
        }
        return _api;
      };
      _api["arguments"] = function() {
        return _arguments = arguments;
      };
      return _api;
    };

    Client.prototype.execute = function(request, callback) {};

    Client.prototype.getAuth = function() {};

    Client.prototype.generateAuthUrl = function() {};

    Client.prototype.getToken = function() {};

    Client.prototype.refreshToken = function() {};

    return Client;

  })();

  module.exports = Client;

}).call(this);
