// Generated by CoffeeScript 1.6.3
(function() {
  var Gcalendar, OAuth2Client, gapi,
    __slice = [].slice;

  gapi = require('googleapis');

  OAuth2Client = gapi.OAuth2Client;

  Gcalendar = (function() {
    function Gcalendar(options) {
      var access_token, client_id, client_secret, redirect_uri, refresh_token, _ref;
      this.options = options != null ? options : {};
      _ref = this.options, client_id = _ref.client_id, client_secret = _ref.client_secret, redirect_uri = _ref.redirect_uri, access_token = _ref.access_token, refresh_token = _ref.refresh_token;
      this.auth = new OAuth2Client(client_id, client_secret, redirect_uri);
      if ((access_token != null) && (refresh_token != null)) {
        this.auth.credentials = {
          access_token: access_token,
          refresh_token: refresh_token
        };
      }
    }

    Gcalendar.prototype.execute = function(request, callback) {
      var e;
      if (callback == null) {
        callback = function() {};
      }
      try {
        return request.withAuthClient(this.auth).execute(callback);
      } catch (_error) {
        e = _error;
        return callback(e);
      }
    };

    Gcalendar.prototype.api = function(query) {
      var _api,
        _this = this;
      _api = function() {
        var args, callback;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (typeof args[args.length - 1] === 'function') {
          callback = args.splice(args.length - 1)[0];
        } else {
          callback = function() {};
        }
        return _this.getClient(function(err, client) {
          var steps, _method;
          if (err != null) {
            return callback(err);
          }
          _method = {};
          steps = query.split('.');
          steps.unshift('calendar');
          steps.every(function(prop) {
            return _method = _method[prop] || client[prop];
          });
          if (typeof _method !== 'function') {
            return callback(new Error("No Such Api! " + query));
          }
          return _this.execute(_method.apply(client, args), function(err, result) {
            if (err != null) {
              err = new Error(err);
            }
            return callback(err, result);
          });
        });
      };
      return _api;
    };

    Gcalendar.prototype.getClient = function(callback) {
      var _this = this;
      if (callback == null) {
        callback = function() {};
      }
      if (this._client != null) {
        return callback(null, this._client);
      }
      return gapi.discover('calendar', 'v3').execute(function(err, client) {
        _this._client = client;
        return callback(err, client);
      });
    };

    Gcalendar.prototype.getAuth = function() {
      return this.auth;
    };

    Gcalendar.prototype.generateAuthUrl = function(callback) {
      var url;
      if (callback == null) {
        callback = function() {};
      }
      url = this.auth.generateAuthUrl({
        access_type: 'offline',
        scope: 'https://www.googleapis.com/auth/calendar',
        approval_prompt: 'force'
      });
      callback(null, url);
      return url;
    };

    Gcalendar.prototype.getToken = function(code, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.auth.getToken(code, function(err, result) {
        if (err != null) {
          err = new Error(err);
        }
        return callback(err, result);
      });
    };

    Gcalendar.prototype.refreshToken = function(callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.auth.refreshAccessToken(function(err, result) {
        if (err != null) {
          err = new Error(err);
        }
        return callback(err, result);
      });
    };

    return Gcalendar;

  })();

  module.exports = Gcalendar;

}).call(this);
