// Generated by CoffeeScript 1.6.3
(function() {
  var api, axon, rpc, server;

  axon = require('axon');

  rpc = require('axon-rpc');

  api = require('api');

  server = function() {
    var rep;
    rep = axon.socket('rep');
    server = new rpc.Server(rep);
    rep.bind(4133);
    return server.expose(api);
  };

  module.exports = server;

}).call(this);
