// Generated by CoffeeScript 1.6.3
(function() {
  var api, axon, rpc, server;

  axon = require('axon');

  rpc = require('axon-rpc');

  api = require('./api');

  server = function() {
    var rep;
    rep = axon.socket('rep');
    server = new rpc.Server(rep);
    rep.bind(5187);
    server.expose(api);
    return console.log('gcalendar serving');
  };

  module.exports = server;

}).call(this);
